Update ec2snap

diff --git a/utilities/ec2snap b/utilities/ec2snap
--- a/utilities/ec2snap
+++ b/utilities/ec2snap
@@ -6,24 +6,43 @@ LOG_DIR="/var/log/ec2snap"
 LOG_FILE="$LOG_DIR/backup_log_$(date +%Y%m%d).txt" # Nombre del archivo de registro
 BACKUP_DIR="/var/ec2snap" # Directorio temporal para archivo comprimido
 BACKUP_FILE="snapshot_$(date +%Y%m%d_%H%M%S).tar.gz" # Nombre del archivo de respaldo
-# Función para comprobar si la ruta de respaldo está montada
+# Función para comprobar si la ruta de respaldo está montada y, en caso negativo, montar una unidad disponible
 function check_mount() {
     # Comprobar si la ruta de respaldo está montada
     echo "Comprobando si la ruta de respaldo está montada..."
     mount_point=$(df --output=target "$BACKUP_DIR" | tail -n 1)
     if [ "$mount_point" != "$BACKUP_DIR" ]; then
         echo "La ruta de respaldo '$BACKUP_DIR' no está montada."
-        # Aquí puedes agregar el procedimiento de montaje adecuado para tu sistema
-        # Por ejemplo, puedes usar el comando 'mount' con los parámetros necesarios
-        # o invocar otro script para montar la unidad requerida.
-        # Después de montar la unidad, puedes verificar nuevamente si está montada correctamente.
-        # Si el montaje es exitoso, puedes continuar con la copia de seguridad.
-        # De lo contrario, puedes mostrar un mensaje de error y salir del script.
+        
+        # Obtener una lista de las unidades disponibles en el sistema
+        available_drives=$(lsblk -rpo "NAME,TYPE,MOUNTPOINT" | awk '$2=="disk" && $3=="" {print $1}')
+
+        if [ -z "$available_drives" ]; then
+            echo "No se encontraron unidades disponibles en el sistema."
+            exit 1
+        fi
+
+        echo "Unidades disponibles en el sistema:"
+        echo "$available_drives"
+
+        # Montar la primera unidad disponible
+        drive_to_mount=$(echo "$available_drives" | head -n 1)
+
+        echo "Montando la unidad '$drive_to_mount' en '$BACKUP_DIR'..."
+        sudo mount "/dev/$drive_to_mount" "$BACKUP_DIR"
+        
+        # Verificar si el montaje fue exitoso
+        mount_point=$(df --output=target "$BACKUP_DIR" | tail -n 1)
+        if [ "$mount_point" != "$BACKUP_DIR" ]; then
+            echo "Error al montar la unidad '$drive_to_mount' en '$BACKUP_DIR'."
+            exit 1
+        else
+            echo "La unidad '$drive_to_mount' se ha montado correctamente en '$BACKUP_DIR'."
+        fi
     else
         echo "La ruta de respaldo '$BACKUP_DIR' está montada."
     fi
 }
-
 # Función para verificar la existencia del directorio temporal para archivo comprimido
 function check_log_dir() {
     # verificar la existencia del directorio temporal
